### PR TITLE
Proposed fix for networkx removed function

### PR DESCRIPTION
**Pull request by pmoulos**
A proposed fix for #51

### CODE REVIEW

**Comment by fenderglass** [comment]
Thanks - does this solution support networkx 2.2 as well? Have you tested it with both Py 2 and 3?

**Comment by pmoulos** [comment]
Hi @fenderglass, I didn't change `requirements.txt` so it works with networkx 2.2.  Also just tested with Python 3 and it works.

**Comment by fenderglass** [comment]
Because the API has changed between 2.2 and 2.3 (`connected_components_subgraphs` -> `connected_components`), I suspect 2.2 support might be broken. The fix needs to be tested with networkx 2.2 (and networkx 2.3) environments separately to ensure that both are working.

**Comment by pmoulos** [comment]
Checked with networkx 2.2, 2.3 and 2.4 - seems to be working.

**Comment by fenderglass** [comment]
Thanks a lot, merged!

**Pull request merged**
